# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/administrator/code/sourcecode/KCFLearn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/administrator/code/sourcecode/KCFLearn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/administrator/code/sourcecode/KCFLearn/CMakeFiles /home/administrator/code/sourcecode/KCFLearn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/administrator/code/sourcecode/KCFLearn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kcf_vot

# Build rule for target.
kcf_vot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kcf_vot
.PHONY : kcf_vot

# fast build rule for target.
kcf_vot/fast:
	$(MAKE) -f CMakeFiles/kcf_vot.dir/build.make CMakeFiles/kcf_vot.dir/build
.PHONY : kcf_vot/fast

#=============================================================================
# Target rules for targets named kcf

# Build rule for target.
kcf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kcf
.PHONY : kcf

# fast build rule for target.
kcf/fast:
	$(MAKE) -f src/CMakeFiles/kcf.dir/build.make src/CMakeFiles/kcf.dir/build
.PHONY : kcf/fast

#=============================================================================
# Target rules for targets named fhog

# Build rule for target.
fhog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fhog
.PHONY : fhog

# fast build rule for target.
fhog/fast:
	$(MAKE) -f src/piotr_fhog/CMakeFiles/fhog.dir/build.make src/piotr_fhog/CMakeFiles/fhog.dir/build
.PHONY : fhog/fast

kcftracker.o: kcftracker.cpp.o

.PHONY : kcftracker.o

# target to build an object file
kcftracker.cpp.o:
	$(MAKE) -f CMakeFiles/kcf_vot.dir/build.make CMakeFiles/kcf_vot.dir/kcftracker.cpp.o
.PHONY : kcftracker.cpp.o

kcftracker.i: kcftracker.cpp.i

.PHONY : kcftracker.i

# target to preprocess a source file
kcftracker.cpp.i:
	$(MAKE) -f CMakeFiles/kcf_vot.dir/build.make CMakeFiles/kcf_vot.dir/kcftracker.cpp.i
.PHONY : kcftracker.cpp.i

kcftracker.s: kcftracker.cpp.s

.PHONY : kcftracker.s

# target to generate assembly for a file
kcftracker.cpp.s:
	$(MAKE) -f CMakeFiles/kcf_vot.dir/build.make CMakeFiles/kcf_vot.dir/kcftracker.cpp.s
.PHONY : kcftracker.cpp.s

runtracker.o: runtracker.cpp.o

.PHONY : runtracker.o

# target to build an object file
runtracker.cpp.o:
	$(MAKE) -f CMakeFiles/kcf_vot.dir/build.make CMakeFiles/kcf_vot.dir/runtracker.cpp.o
.PHONY : runtracker.cpp.o

runtracker.i: runtracker.cpp.i

.PHONY : runtracker.i

# target to preprocess a source file
runtracker.cpp.i:
	$(MAKE) -f CMakeFiles/kcf_vot.dir/build.make CMakeFiles/kcf_vot.dir/runtracker.cpp.i
.PHONY : runtracker.cpp.i

runtracker.s: runtracker.cpp.s

.PHONY : runtracker.s

# target to generate assembly for a file
runtracker.cpp.s:
	$(MAKE) -f CMakeFiles/kcf_vot.dir/build.make CMakeFiles/kcf_vot.dir/runtracker.cpp.s
.PHONY : runtracker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kcf_vot"
	@echo "... kcf"
	@echo "... fhog"
	@echo "... kcftracker.o"
	@echo "... kcftracker.i"
	@echo "... kcftracker.s"
	@echo "... runtracker.o"
	@echo "... runtracker.i"
	@echo "... runtracker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

